# Generated by Django 2.2.6 on 2021-06-03 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20210602_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='count',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество'),
        ),
    ]
