# Generated by Django 2.2.6 on 2021-06-11 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_auto_20210608_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='slug',
        ),
    ]
